name: Tests

# Run on Pull Request to $branch only
on: [push]

# Job Setup
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 #Checkout Repo
    - uses: actions/setup-node@v1 #Setup Node
      with:
        node-version: '22'
    - name: Run Jest Tests
      run: |
        npm install
        npm run test
      timeout-minutes: 5
  web-ext:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 #Checkout Repo
    - name: Install
      run: |
        npm install
        mkdir external
        cp node_modules/webextension-polyfill/dist/browser-polyfill.min.js external/browser-polyfill.min.js
    - name: Web-ext lint
      uses: kewisch/action-web-ext@v1
      with:
        cmd: lint
        channel: listed

